showDropdown expose alignment & offset modifier from showPopover
sunarya-thito/shadcn_flutter pull request #62
Opened 2024-08-23 16:31 UTC by cyberpwnn

Was using showDropdown and noticed this should probably be in here at least as an option otherwise the developer would have to copy the showDropdown method and use showPopover instead. This change does not change the default undefined behavior as the default parameters result in the same call to showPopover. 

Also, amazing work on this project so far, Starting to use it and its lovely.

2024-08-28 11:09 UTC, sunarya-thito requested changes

2024-08-28 11:09 UTC, sunarya-thito commented on lib/src/components/menu/dropdown_menu.dart
> +  Alignment alignment = Alignment.topCenter,
I think this should be AlignmentGeometry instead of Alignment to support RTL text direction, as shown in [`showPopover`](https://github.com/sunarya-thito/shadcn_flutter/blob/master/lib/src/components/overlay/popover.dart#L447)

2024-08-28 11:09 UTC, sunarya-thito commented on lib/src/components/menu/dropdown_menu.dart
> +  Offset offset = Offset.zero,
`offset` should be nullable and set default to null, see my other code review below

2024-08-28 11:09 UTC, sunarya-thito commented on lib/src/components/menu/dropdown_menu.dart
> +    offset: (const Offset(0, 4) * scaling) + offset,
When overriding, it shouldn't use the default value, You might wanna do it something like this:
```dart
showPopover(
    ...
    offset: offset == null ? (const Offset(0, 4) * scaling) : offset,
    ...
)
```
so that, whenever the offset parameter is filled, it won't add an extra offset from the default value

2024-08-28 11:14 UTC, sunarya-thito commented
mb, forgot to submit my review, please change it as advised, sorry for the delay.

2024-09-08 21:29 UTC, cyberpwnn commented
I was just forwarding the popover parameters, If you want to change that method also it's beyond the "fix" I was going for. It was just impossible to use menus as they were hiding the alignment properties.

2024-09-08 21:29 UTC, closed without merging

2024-09-09 02:20 UTC, sunarya-thito commented
What I meant to say was, that your PR request is good, it just needs a little bit modification as I stated in my PR review, I don't know why you closed this PR.